#### PyTorch 
1. PyTorch의 개요 
    * PyTorch 는 2017년 초에 공개된 Deep-Learning Framework로 Lua 언어로 개발되었던 Torch를 Facebook에서 Python 버전으로 내놓은 것이다 .
    * Torch는 Python의 Numpy Library처럼 과학연산을 위한 Library로 공개되었지만 이후 발전을 거듭하면서 Deep-Learning Framework로 발전 
    * PyTorch는 Python 기반의 과학 연산 package로 다음 두 집단을 대상으로 한다. 
        - Numpy를 대체하면서 GPU를 이용한 연산이 필요한 경우 
        - 최대한의 유연성과 속도를 제공하는 Deep-Learning 연구 Platform 이 필요한 경우  
2. PyTorch의 특징 및 장점 
    * GPU에서 tensor 조작 및 동적 신경망 구축이 가능한 Framework 
    * GPU(Graphics Processing Unit) 
        - 연산속도를 빠르게 하는 역할 
        - Deep-Learning에서는 기울기를 계산할 때 미분을 쓰는데 GPU를 사용하면 빠른 계산이 가능 
        - 내부적으로 CUDA, cuDNN이라는 API를 통해서 GPU를 연산에 적용 가능하다. 
    * Tensor 
        - tensor은 PyTorch의 데이터 형태이다. 
        - tensor안 단일 데이터 형식으로 된 다차원의 행렬이다. 
        - tensor는 간단한 명령어(변수 뒤에 cuda()를 추가)를 사용해서 GPU로 연산을 수행하게 할 수 있다. 
    * 동적 신경망 
        - 훈련을 반복할 때 마다 변경이 가능한 신경망을 의미한다. 

2. PyTorch의 Architecture 
    * PyTorch의 Architecture는 크게 세개의 층으로 구분 
    * 첫번째 계층 : PyTorch API
        - 이 계층에서는 사용자가 이해하기 쉬운 API를 제공하여 Tensor에 대한 처리와 신경망을 구축하고 훈련할 수 있도록 돕는다. 
        - 이 계층에서는 사용자 인터페이스를 제공하지만 실제 계산을 수행하지 않는다. 
        - torch 
            - GPU를 지원하는 tensor package 
        - torch.autigrabm 
            - Autograb는 tensorflow, Caffe, CNTK와 같은 다른 Deep-Learning 와 가장 차별되는 package 이다. 
            - 일반적으로 신경멍에서 사소한 변경이 있다면 신경망 구축을 처음부터 다시 시작해야 한다. 하지만 PyTorch는 자동 미분(auto-differentiation) 을 이용하여 미분 계산을 효율적으로 처리한다.  
        - torch.nn
            - 신경망 구축 및 훈련 package 
            
        - torch.multiprocessing 
             - PyTorch에서 사용하는 프로세스 전반에 걸쳐서 tensor의 메모리 공유가 가능하다. 따라서 다른 프로세스에서 동일한 tensor에 대한 접근 및 사용이 가능하다. 
        - torch.utils  
            - 기타 유틸리티를 제공하는 패키지
    * 두번째 층 : PyTorch Engine
        - Autograd C++ 
            - 가중치와 편향을 업데이트하는 과정에서 필요한 미분을 자동으로 계산하는 해주는 역할 
        - Aten C++
            - C++ tensor library 제공  
        - JIT C++
            - 계산을 최적화하기 위한 JIT(Just In-Time) Compiler 
    * 세번째 층 : 연산 처리 
        - TH C 
        - TH CUDA 
        - THNN C 
        - THCUNN CUDA 

In [2]:
import torch 

In [ ]:
print(torch.tensor([[1, 2], [3, 4]]))
print(torch.tensor([[1, 2], [3, 4]], dtype=torch.float64))
temp = torch.tensor([[1, 2], [3, 4]])
print(temp.numpy())

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
[[1 2]
 [3 4]]


In [ ]:
temp = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7])
print(temp[0], temp[1], temp[2])
print(temp[2:5])
print(temp[4:-1])
print(temp[:-1])

tensor(1.) tensor(2.) tensor(3.)
tensor([3., 4., 5.])
tensor([5., 6.])
tensor([1., 2., 3., 4., 5., 6.])


#### tenosr 연산 및 조작 

In [ ]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([3, 4, 5])
print(v - w)

tensor([-2, -2, -2])


tensor 차원 및 조작 

In [11]:
# 2 * 2 matrix 
temp = torch.tensor([[1, 2], [3, 4]])
print(f"length :{len(temp)}")
print(f"shape :{temp.shape}") 
print(f"type :{type(temp)}")

# 4 * 1 matrix 
print(temp.view(4, 1))
temp = temp.view(4,1)
print(temp.shape)

# 1 * 4 matrix 
temp= temp.view(1, -1)
print(temp.shape)

# 1 * 1* 4 matrix 
temp = temp.view(1, 1, 4, 1)
print(temp)

length :2
shape :torch.Size([2, 2])
type :<class 'torch.Tensor'>
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])
torch.Size([1, 4])
tensor([[[[1],
          [2],
          [3],
          [4]]]])
