#### Machine Learning 
1. Supervised Learning 
* Supervised Learning은 Label(정답)을 컴퓨터에 미리 알려주고 데이터를 학습시키는 방법 
* classification : 주어진 데이터를 정해진 분률에 따라 분류
* regression : 주어진 데이터의 특성(feature)을 기준으로 연속된 값을 그래프로 표현하야 패턴이나 트렌드를 예측 

|구분|분류|회귀|
|---|---|----|
|데이터 유형|이산형데이터|연속형데이터|
|결과|훈련데이터의 레이블 중 하나를 예측| 연속된 값의 예측|
|예시| 학습 데이터를 A-B-C 그룹 중 하나로 매핑|결과 값이 어떤 값이든 나올 수 있음|

2. Supervised Learning 
    1. K-NN(Nearest neighbor) 
        - K-NN은 새로운 입력(학습에 사용되지 않은 새로운 데이터)를 받았을 때 기존 클러스터에서 모든 데이터와 인스턴스 기반 거리를 측정한 후 가장 많은 속성을 가진 클러스터에 할당하는 알고리즘 
        - 과거 데이터를 사용하여 미리 분류 모형을 만드는 것이 아니라 과거 데이터를 저장해 두고 필요할 때마다 비교를 수행하는 방식 
        - K 값의 선택에 따라 새로운 데이터에 대한 분류가 달라짐 



In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
from google.colab import drive 
from sklearn import metrics 

In [15]:
from sklearn.model_selection import train_test_split 

In [3]:
drive.mount("/content/drive/")
FILE_PATH = "/content/drive/MyDrive/dataset/pytorch/iris.data"

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [8]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.read_csv(FILE_PATH, names=names)

In [9]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [14]:
X = dataset.iloc[:, :-1 ].values
Y = dataset.iloc[:, 4].values
print(X.shape)
print(Y.shape)


(150, 4)
(150,)


In [33]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size= 0.20, random_state = 4)

In [34]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()
print(x_train)
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)
print(x_train)

[[5.4 3.  4.5 1.5]
 [4.6 3.2 1.4 0.2]
 [6.7 2.5 5.8 1.8]
 [4.9 3.  1.4 0.2]
 [5.  2.3 3.3 1. ]
 [6.7 3.3 5.7 2.5]
 [7.2 3.2 6.  1.8]
 [5.8 2.6 4.  1.2]
 [6.7 3.1 4.7 1.5]
 [5.1 3.8 1.6 0.2]
 [7.7 3.  6.1 2.3]
 [5.  3.4 1.5 0.2]
 [6.7 3.1 4.4 1.4]
 [5.4 3.7 1.5 0.2]
 [6.4 2.8 5.6 2.2]
 [4.3 3.  1.1 0.1]
 [5.7 4.4 1.5 0.4]
 [5.9 3.  4.2 1.5]
 [6.1 3.  4.6 1.4]
 [6.5 3.  5.5 1.8]
 [5.2 3.5 1.5 0.2]
 [5.6 2.5 3.9 1.1]
 [7.7 2.6 6.9 2.3]
 [6.3 3.4 5.6 2.4]
 [6.2 2.9 4.3 1.3]
 [5.7 2.9 4.2 1.3]
 [5.  3.5 1.6 0.6]
 [5.6 2.9 3.6 1.3]
 [6.  2.2 5.  1.5]
 [5.5 2.6 4.4 1.2]
 [4.6 3.4 1.4 0.3]
 [5.6 3.  4.1 1.3]
 [5.1 3.4 1.5 0.2]
 [6.4 2.9 4.3 1.3]
 [6.8 3.  5.5 2.1]
 [6.7 3.  5.  1.7]
 [6.5 3.2 5.1 2. ]
 [6.  3.4 4.5 1.6]
 [4.9 3.1 1.5 0.1]
 [4.9 2.5 4.5 1.7]
 [6.9 3.2 5.7 2.3]
 [5.4 3.4 1.5 0.4]
 [5.5 2.4 3.8 1.1]
 [6.3 3.3 6.  2.5]
 [5.  3.6 1.4 0.2]
 [6.1 3.  4.9 1.8]
 [6.5 2.8 4.6 1.5]
 [5.9 3.  5.1 1.8]
 [6.3 2.5 4.9 1.5]
 [4.9 3.1 1.5 0.1]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 1.5]
 [7.1 3.  5.

In [35]:
from sklearn.neighbors import  KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 50)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=50)

In [36]:
from sklearn.metrics import accuracy_score 
y_predict = knn.predict(x_test)
print(f"accuracy : {accuracy_score(y_test, y_predict)}")

accuracy : 0.9


In [38]:
k = 10
acc_array = np.zeros(k)
for k in np.arange(1, k+1, 1): 
    classifier = KNeighborsClassifier(n_neighbors=k).fit(x_train, y_train)
    accuracy = metrics.accuracy_score(y_test, y_pred)
    acc_array[k-1] = accuracy

max_accuracy = np.amax(acc_array)
accuracy_list = list(acc_array)
k = accuracy_list.index(max_accuracy) 
print(f"accuracy {max_accuracy} best k value {k+1}")


accuracy 0.23333333333333334 best k value 1
